### ISSUE TITLE
more issues with initial elements, etc

### ISSUE THREAD

**Issue by lispm** [mare5x/LispQR#5]
The code has a bunch more issues:

* adjust-array returns the adjusted array. In the code this array is not used. adjust-array also needs an initial element

* all make-list need an initial-element

* vector-push-extend calls adjust-array, but one can't specify an initial-element to vector-push-extend. -> extend only by 1 in the code would be a fix

* all make-array for integer arrays need an initial-element

Otherwise I can see that LispWorks and SBCL create different results.

**Comment by mare5x** [comment]
Ok, I'll look into it when I get the time. As for LispWorks and SBCL, I only tested using Portacle (SBCL). I might give LispWorks a try as well.

**Comment by mare5x** [comment]
I made the changes you proposed and it seems that the LispWorks issues are also gone now. Great!
